### PR TITLE
Fixes #30910 - Better option assignment for nested params

### PR DESCRIPTION
**Pull request by ofedoren**
~~Because `params['host']['compute_attributes']` was being set to an empty hash even if the option was not provided, the redundant param was being sent to the server. That's not quite right.~~

Also, which is more important, I've noticed (thanks to the test in this PR) that there is some mess with those nested hash params:
` $ hammer host update --id 4 --new-name lera `
ScreenShot-1600950263532
ScreenShot-1600950360150

~~Even though the server ignores redundant stuff, I guess we should fix that as well: https://projects.theforeman.org/issues/30910~~

Requires https://github.com/theforeman/hammer-cli/pull/336.

### CODE REVIEW

**Comment by Pigueiras** [comment]
@ofedoren I was trying this PR and I still see the `compute_attributes => {}` 🤔 

```
$ hammer --debug host update --name monitoring.example.org --hostgroup-title monitoring/prometheus
...
[ INFO 2020-09-25T13:38:36 API] PUT /api/hosts/18
[DEBUG 2020-09-25T13:38:36 API] Params: {
    "host" => {
                      "name" => "monitoring.example.org",
              "hostgroup_id" => 18,
        "compute_attributes" => {}
    }
}
...
```

**Comment by ofedoren** [comment]
> @ofedoren I was trying this PR and I still see the `compute_attributes => {}` 
> 
> ```
> $ hammer --debug host update --name monitoring.example.org --hostgroup-title monitoring/prometheus
> ...
> [ INFO 2020-09-25T13:38:36 API] PUT /api/hosts/18
> [DEBUG 2020-09-25T13:38:36 API] Params: {
>     "host" => {
>                       "name" => "monitoring.example.org",
>               "hostgroup_id" => 18,
>         "compute_attributes" => {}
>     }
> }
> ...
> ```

Actually, I think it's a bug in core, so this should fix that: https://github.com/theforeman/hammer-cli/pull/336

**Comment by Pigueiras** [comment]
> > @ofedoren I was trying this PR and I still see the `compute_attributes => {}`
> > ```
> > $ hammer --debug host update --name monitoring.example.org --hostgroup-title monitoring/prometheus
> > ...
> > [ INFO 2020-09-25T13:38:36 API] PUT /api/hosts/18
> > [DEBUG 2020-09-25T13:38:36 API] Params: {
> >     "host" => {
> >                       "name" => "monitoring.example.org",
> >               "hostgroup_id" => 18,
> >         "compute_attributes" => {}
> >     }
> > }
> > ...
> > ```
> 
> Actually, I think it's a bug in core, so this should fix that: [theforeman/hammer-cli#336](https://github.com/theforeman/hammer-cli/pull/336)

Amazing! It works now with the patch in core 👍

**Comment by ofedoren** [comment]
For reviewer: I've changed this PR so it fixes different issue (https://projects.theforeman.org/issues/30910), which is quite related to the fix in core (https://github.com/theforeman/hammer-cli/pull/336).

**Comment by shiramax** [comment]
@ofedoren I think this issue might be relevant only for katello, 
I can't see this issue: 
[ INFO 2020-10-07T10:20:36 API] Server: http://localhost:3000
[ INFO 2020-10-07T10:20:36 API] PUT /api/hosts/24
[DEBUG 2020-10-07T10:20:36 API] Params: {
    "host" => {
        "compute_attributes" => {},
                      "name" => "lera"
    },
    "name" => "lera"
}
[DEBUG 2020-1

**Review by shiramax — APPROVED** [review]

**Comment by shiramax** [comment]
Thanks @ofedoren !

**Pull request merged**
