### PR TITLE
Fixes #11279 - Fixed updating host owner when ownertype is Usergroup

### PR DESCRIPTION
**Pull request by yifatmakias**

### CODE REVIEW

**Comment by yifatmakias** [comment]
I will open a separate PR to update search_options creators.
Thanks for the review :)

**Comment by ofedoren** [comment]
Thanks @yifatmakias! With related katello PR works as expected. But could you please add some tests to track it will not be broken in future?

**Comment by yifatmakias** [comment]
Yes, I will add some tests.

**Comment by ofedoren** [comment]
[test hammer]

**Comment by ofedoren** [comment]
@yifatmakias, everything is done, thus merging. Thanks! :)

**Pull request merged**
