### PR TITLE
Fixes #33438 - Fix puppet-class command description

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Should we disregard tests when running against stable branches? The proposed changes looks fine and can't possibly cause all that breakage

**Comment by ofedoren** [comment]
@adamruzicka, I guess we can simply ignore that if the tests pass locally (which they do). Such PRs into a stable branch are rare, we do CPs instead manually when we are about to release a new minor version, so we run tests locally against the current stable branch anyway.

**Review by adamruzicka — APPROVED** [review]
LGTM

**Comment by ofedoren** [comment]
@adiabramovitch, could you please take a look/merge? :)

**Pull request merged**
