### PR TITLE
Add Catalan language

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by tstrachota** [comment]
Thank you @rbuj! Unfortunately my testing showed there is a bug in the `table_print` library that we use for output of `list` commands. It fails on listing any column containing dot in the label. Your Catalan translation maps `"Id"` to `"Id."` and therefore every `list` command fails with the switched locale.

Until this bug is fixed, is it essential to keep the dots there?

```
LC_ALL=ca_ES hammer host list
To disable read timeouts, please set timeout to nil instead of -1
/root/hammer/hammer-cli/lib/hammer_cli/output/adapter/table.rb:121:in `[]': no implicit conversion from nil to integer (TypeError)
        from /root/hammer/hammer-cli/lib/hammer_cli/output/adapter/table.rb:121:in `block (2 levels) in sort_columns'
        from /root/hammer/hammer-cli/lib/hammer_cli/output/adapter/table.rb:121:in `each'
        from /root/hammer/hammer-cli/lib/hammer_cli/output/adapter/table.rb:121:in `block in sort_columns'
        from /root/hammer/hammer-cli/lib/hammer_cli/output/adapter/table.rb:107:in `each'
        from /root/hammer/hammer-cli/lib/hammer_cli/output/adapter/table.rb:107:in `sort_columns'
        from /root/hammer/hammer-cli/lib/hammer_cli/output/adapter/table.rb:50:in `print_collection'
        from /root/hammer/hammer-cli/lib/hammer_cli/output/output.rb:27:in `print_collection'
        from /root/hammer/hammer-cli/lib/hammer_cli/abstract.rb:167:in `print_collection'
        from /root/hammer/hammer-cli/lib/hammer_cli/apipie/command.rb:62:in `print_data'
        from /root/hammer/hammer-cli-foreman/lib/hammer_cli_foreman/commands.rb:294:in `execute'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /root/hammer/hammer-cli/lib/hammer_cli/abstract.rb:23:in `run'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /root/hammer/hammer-cli/lib/hammer_cli/abstract.rb:23:in `run'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /root/hammer/hammer-cli/lib/hammer_cli/abstract.rb:23:in `run'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
        from ./bin/hammer:125:in `<main>'
```
(please note that the stacktrace points to hammer but the exception occurs based on previous failures from `table_print`)

**Comment by rbuj** [comment]
Id. -> ID (https://www.softcatala.org/recull.html)

**Comment by tstrachota** [comment]
@rbuj I didn't notice you changed the translations together with your comment. I'm sorry! Merged as 86f18d828d193d99d70581462ee541c0f7780586

**Comment by rbuj** [comment]
no problem, thanks!

**Pull request closed without merging**
