### PR TITLE
Fixes #23204 - Consistent puppet environment naming in hammer

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by mbacovsky** [comment]
[test hammer]

**Comment by akofink** [comment]
Oddly, this doesn't seem to break any of the hammer-cli-katello tests. The main lifecycle environment code in h-c-k is [this mapping module](https://github.com/Katello/hammer-cli-katello/blob/master/lib/hammer_cli_katello/lifecycle_environment_name_mapping.rb) and [the resolvable module](https://github.com/Katello/hammer-cli-katello/blob/master/lib/hammer_cli_katello/lifecycle_environment_name_resolvable.rb). I'm quite sure I'm very happy about this change - perhaps hammer-cli-katello can push to name all --environment options to --lifecycle-environment in the future as well. This conflation has caused lots of issues in the past.

**Comment by ofedoren** [comment]
@mbacovsky, updated. But now it requires https://github.com/theforeman/hammer-cli/pull/291. Also fixed the issue when `host update --puppet-environment Name` triggered resolving of lifecycle environments, see: https://github.com/Katello/hammer-cli-katello/pull/629

**Comment by mbacovsky** [comment]
[test hammer]

**Comment by ofedoren** [comment]
Please, don't merge for now. I found out that it's not ready yet (even though I've tested before).

**Comment by ofedoren** [comment]
@mbacovsky. updated. Seems to be working now, but I'm not sure how it will behave with `ids` resolution.. Can you please provide a good example for testing it?

Also, see https://github.com/Katello/hammer-cli-katello/pull/629 for testing with lifecycle environments.

**Comment by mbacovsky** [comment]
@ofedoren thanks for the update. My previous concerns were fixed. 
It was good point with the environment_ids. I did a quick research with `hammer full-help|grep -B50 -E "environment-ids|environments"` and it revealed some missing conversions:
- organization > update
- organization > create
- location > update
- location > create
- content-view > version > promote (also --environments is missing, not sure if intentionally)
- content-view > remove

Is that what you were looking for?

**Comment by ofedoren** [comment]
@mbacovsky, updated. I've added `ids` support (for katello as well in the mentioned above PR) and it seems to be working.

**Comment by johnpmitsch** [comment]
@mbacovsky @ofedoren What is the status of this PR? I confirmed that it fixes an additional issue with hostgroups related to puppet-environments: https://bugzilla.redhat.com/show_bug.cgi?id=1713222

**Comment by shiramax** [comment]
Thanks, @ofedoren ! Great work :)

**Pull request merged**
