### PR TITLE
Fixes #23996 - Hammer asks for user password though -p option provided

### PR DESCRIPTION
**Pull request by apuntamb**

### CODE REVIEW

**Comment by mbacovsky** [comment]
@apuntamb thanks for updating the PR and for the new test! It works now as expected and in general it is good to go. 

While investigating how to approach the tests for this addition I found out that the existing user update tests do not work properly and some features are not tested. I tried to fixed that and ended up with tests also for your addition. I added it as a new PR to your branch: https://github.com/apuntamb/hammer-cli-foreman/pull/1. I'll ask @tstrachota for review there and once it is ACKed you can merge and we can merge this PR with both commits too.

**Comment by apuntamb** [comment]
@mbacovsky  Sure, thank you for the updates and the tests as well.

**Comment by tstrachota** [comment]
@mbacovsky I didn't test your PR but it looks fine. I like that you added the "block signature".

**Comment by mbacovsky** [comment]
@tstrachota thanks for the review!  @apuntamb could you merge my PR to your branch? We can merge this PR then when the tests pass.

**Comment by apuntamb** [comment]
thanks @tstrachota for reviewing. @mbacovsky your PR has been merged into my branch. could you now take a look.

**Comment by mbacovsky** [comment]
:+1: Thanks @apuntamb! LGTM now.

**Pull request merged**
