### PR TITLE
Fixes #9906 - Align subnet translations in hammer with UI

### PR DESCRIPTION
**Pull request by apuntamb**

### CODE REVIEW

**Comment by lzap** [comment]
Looks good, but I'd probably push this further and reorder things a bit:

```
[lzap@box hammer-cli-foreman]$ hammer-quick subnet info --name subnet_99
Id:            2
Name:          subnet_99
Network:       192.168.99.0
CIDR:          24
Mask:          255.255.255.0
VLAN ID:       11
Boot Mode:     DHCP
Description:   
  Internal DB dummy net
Priority:      
DNS:           localhost (http://localhost:8448)
Primary DNS:   192.168.99.1
Secondary DNS: 
TFTP:          localhost (http://localhost:8448)
DHCP:          localhost (http://localhost:8448)
IPAM:          DHCP
Gateway:       192.168.99.1
From:          192.168.99.10
To:            192.168.99.220
MTU:           1500
Domains:       
    home.lan
Locations:     
    MyLoc
    TestLoc
Organizations: 
    MyOrg
    SecondOrg
Parameters:
```

My proposal:

```
Id:            2
Name:          subnet_99
Priority:      
Network:       192.168.99.0
Mask:          255.255.255.0
CIDR:          24
IPAM:          DHCP
Boot Mode:     DHCP
Gateway:       192.168.99.1
From:          192.168.99.10
To:            192.168.99.220
Primary DNS:   192.168.99.1
Secondary DNS: 
VLAN ID:       11
MTU:           1500
Description:   
  Internal DB dummy net
Smart-Proxy:
  DNS:           localhost (http://localhost:8448)
  TFTP:          localhost (http://localhost:8448)
  DHCP:          localhost (http://localhost:8448)
Domains:       
    home.lan
Locations:     
    MyLoc
    TestLoc
Organizations: 
    MyOrg
    SecondOrg
Parameters:
```

Now, *how* you can do this - I can't tell. Not hammer expert here.

**Comment by tstrachota** [comment]
+1 for @lzap's re-ordering proposal. It's easy to achieve - hammer prints the fields in the same order as they were defined. Just re-order it in the code.

**Comment by apuntamb** [comment]
@lzap and @tstrachota +1 for the insights.

**Comment by tstrachota** [comment]
Works fine. Thank you for fixing the structure globally @apuntamb !

**Pull request merged**
