### PR TITLE
Refs #22253 - Allow mixing option sources and validations

### PR DESCRIPTION
**Pull request by tstrachota**
This patch makes hammer-cli-katello compatible with changes in:
https://github.com/theforeman/hammer-cli/pull/242

Please see the discussion in the PR into hammer core for more details about the functionality that is going to be merged there.

### CODE REVIEW

**Comment by mbacovsky** [comment]
@tstrachota looks good, tests are green locally and runs flawlessly.
It could be useful to add at least a link to option processors docs in core and full processors stack structure to https://github.com/theforeman/hammer-cli-foreman/blob/master/doc/name_id_resolution.md. What do you think?

**Comment by tstrachota** [comment]
@mbacovsky updated

**Comment by mbacovsky** [comment]
:+1: I'll merge once @akofink confirms hammer-cli-katello is in a good shape with this change and once the tests are green with core part merged

**Comment by tstrachota** [comment]
@mbacovsky would you mind pinging him? Since his last comment was "I want to re-review after the dependent changes are finalized." I'm afraid we could end up in a deadlock :)

**Comment by mbacovsky** [comment]
Tests are green, merging. Thanks @tstrachota, @akofink! :beers:

**Pull request merged**
