### PR TITLE
Fixes #20607 - Allow hiding fields which are missing from api output

### PR DESCRIPTION
**Pull request by ofedoren**
Depends on https://github.com/theforeman/hammer-cli/pull/256

### CODE REVIEW

**Comment by tstrachota** [comment]
@ofedoren could you please elaborate why we need to pass output adapters explicitly in the tests that you changed? I don't understand why the change is needed.

**Comment by ofedoren** [comment]
@tstrachota updated. You was right, there is no need to pass output adapters explicitly, that was a my mistake in implementation core changes.

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
Based on recent changes in the hammer-cli counterpart PR, this is no longer needed. Closing.
@ofedoren thanks for your efforts to keep the plugins compatible.

**Pull request closed without merging**
