### PR TITLE
Fixes #20117 - Correctly reset taxonomies for overriding filters

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by ares** [comment]
Works well, since this was a buggy behavior, could it be covered with test? Otherwise :+1

**Comment by iNecas** [comment]
@tstrachota seems we are close to get this one in?

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
Tests added

**Comment by ares** [comment]
Thanks, :+1: from me :-) (sorry, I though the test would be much smaller)

**Pull request merged**
