### PR TITLE
Refs #30996 - Apply option family on SearchablesOptionBuilder

### PR DESCRIPTION
**Pull request by ofedoren**
Follow up PR for https://github.com/theforeman/hammer-cli/pull/339.

Mostly for katello related stuff.

### CODE REVIEW

**Comment by ofedoren** [comment]
@chris1984, hey. Can you, please, verify if this fixes the described bug in the issue? Sorry for poking you, but you're one of the few who has ready-for-test Katello setup :)

**Comment by chris1984** [comment]
@ofedoren sure, will test today

**Comment by chris1984** [comment]
@ofedoren 

I tried to apply the patch on a fresh hammer-devel box and I am not able to get the patch to apply clean:

```bash
[vagrant@hammer hammer-cli-foreman]$ patch -p1 < 559.patch
patching file lib/hammer_cli_foreman/option_builders.rb
Hunk #2 FAILED at 224.
Hunk #3 FAILED at 256.
Hunk #4 FAILED at 319.
Hunk #5 FAILED at 347.
4 out of 5 hunks FAILED -- saving rejects to file lib/hammer_cli_foreman/option_builders.rb.rej
```

**Comment by ofedoren** [comment]
@chris1984, thank you! Also, my apologies for the delay. I've rebased this and the patch seems to be easy to apply.

Also, you probably want to apply https://github.com/theforeman/hammer-cli/pull/339 on hammer-cli core as well.

Could you please re-test this so we can merge if it fixes the issue?

**Comment by chris1984** [comment]
@ofedoren sure will test today for you

**Review by chris1984 — COMMENTED** [review]
Hey @ofedoren 

I applied both patches but still seeing mismatches:

Normal Help:
```bash
[vagrant@hammer ~]$ hammer content-view add-version --help
Usage:
    hammer content-view add-version [OPTIONS]

Options:
 --content-view[-id]                                 Content view name/id to search by
 --content-view-version[-id]                         Content view version identifier
 --id ID                                             Content view numeric identifier
 --name NAME                                         Content view name to search by
 --organization[-id|-label]                          Organization name/label/id to search by
 -h, --help                                          Print help
```
Full help:
```bash
hammer > content-view > add-version
-----------------------------------
Add a content view version to a composite view

Usage:
    hammer content-view add-version [OPTIONS]

Options:
 --content-view CONTENT_VIEW_NAME                    Content view name to search by
 --content-view-id CONTENT_VIEW_ID                   Content view id to search by
 --content-view-version CONTENT_VIEW_VERSION_VERSION Content view version number
 --content-view-version-id CONTENT_VIEW_VERSION_ID   Content view version identifier
 --id ID                                             Content view numeric identifier
 --name NAME                                         Content view name to search by
 --organization ORGANIZATION_NAME                    Organization name to search by
 --organization-id ORGANIZATION_ID                   Organization ID to search by
 --organization-label ORGANIZATION_LABEL             Organization label to search by
 -h, --help                                          Print help
 ```

**Comment by ofedoren** [comment]
> Hey @ofedoren
> 
> I applied both patches but still seeing mismatches:
> 
> Normal Help:
> 
> ```shell
> [vagrant@hammer ~]$ hammer content-view add-version --help
> Usage:
>     hammer content-view add-version [OPTIONS]
> 
> Options:
>  --content-view[-id]                                 Content view name/id to search by
>  --content-view-version[-id]                         Content view version identifier
>  --id ID                                             Content view numeric identifier
>  --name NAME                                         Content view name to search by
>  --organization[-id|-label]                          Organization name/label/id to search by
>  -h, --help                                          Print help
> ```
> 
> Full help:
> 
> ```shell
> hammer > content-view > add-version
> -----------------------------------
> Add a content view version to a composite view
> 
> Usage:
>     hammer content-view add-version [OPTIONS]
> 
> Options:
>  --content-view CONTENT_VIEW_NAME                    Content view name to search by
>  --content-view-id CONTENT_VIEW_ID                   Content view id to search by
>  --content-view-version CONTENT_VIEW_VERSION_VERSION Content view version number
>  --content-view-version-id CONTENT_VIEW_VERSION_ID   Content view version identifier
>  --id ID                                             Content view numeric identifier
>  --name NAME                                         Content view name to search by
>  --organization ORGANIZATION_NAME                    Organization name to search by
>  --organization-id ORGANIZATION_ID                   Organization ID to search by
>  --organization-label ORGANIZATION_LABEL             Organization label to search by
>  -h, --help                                          Print help
> ```

Thanks, @chris1984! Actually, you've proved that it fixes the issue :) There is `--content-view` option back in normal help.

**Review by chris1984 — APPROVED** [review]
ACK then :)

**Review by yifatmakias — APPROVED** [review]
Thanks @ofedoren.
Looks good to me and according to @chris1984 works as well.
so merging into master.

**Pull request merged**
