### PR TITLE
Fixes #21764 - Add Location and Description Fields

### PR DESCRIPTION
**Pull request by akshay-mendhe**
Adds Location and Description Field for Host Command

### CODE REVIEW

**Comment by akshay-mendhe** [comment]
Added Location field, but what should be there in Description field?

**Comment by akshay-mendhe** [comment]
We can show column "additional information" about host if there is any additional information given while creating host.

**Comment by mbacovsky** [comment]
@akshay-mendhe thank you for the contribution and sorry for not responding for so long. 
The code looks good and I appreciate the test updated. Adding new fields to `host list` is quite sensitive task as it may make the list too wide and difficult to use. 

The long term plan is to make the fields configurable to better match the users needs. While the feature is being worked on (https://github.com/theforeman/hammer-cli/pull/276) currently I'd prefer to wait and update this PR to leverage the new feature when it is merged. I'll update here when that happens. Would that be acceptable?

**Comment by akshay-mendhe** [comment]
Yes, sure Thanks @mbacovsky

**Comment by mbacovsky** [comment]
@chris1984 as I wrote above, extending the host list width is quite sensitive. Especially adding the description will lead to line wraps in the middle and unreadable output. I hope we will merge https://github.com/theforeman/hammer-cli/pull/276 next week and unblock this with new possibilities.

**Comment by ofedoren** [comment]
@mbacovsky, https://github.com/theforeman/hammer-cli/pull/276 is merged, what was your suggestion?

**Comment by mbacovsky** [comment]
My suggestion now is to add the new fields only to ALL set so that the fields are not present in the DEFAULT set:
```ruby7
field nil, _("Location"), Fields::SingleReference, :key => :location, :hide_blank => true, :sets => ['ALL']
field :comment, _("Additional Information"), nil, :sets => ['ALL']
```
then
`hammer host list` won't print them while `hammer host list --fields ALL` will do.
Also the original issue speaks about the organization too so it can be added as well.

**Comment by mbacovsky** [comment]
Note the `--fields` feature require https://github.com/theforeman/hammer-cli/pull/307 to work as expected.

**Comment by mbacovsky** [comment]
@akshay-mendhe could you please rebase and check my previous comments? Would it work for you?

**Comment by kgaikwad** [comment]
@mbacovsky, 
It would be good if we create new pull-request with suggested changes and close this one on behalf of new.  Would it be possible for you? or let me know I will create one.

**Comment by mbacovsky** [comment]
@kgaikwad if that works for you I'm okay with that.

**Comment by kgaikwad** [comment]
@mbacovsky, 
Can we close this pull-request on behalf of [PR-423](https://github.com/theforeman/hammer-cli-foreman/pull/423)?

**Comment by mbacovsky** [comment]
@kgaikwad thanks for the new PR! Closing this one.

**Pull request closed without merging**
