### PR TITLE
i18n - extracting new, pulling from tx

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Review by adamruzicka — COMMENTED** [review]
Huh, I would have expected that the removal of rackspace would have some impact on the strings that get extract, but apparently not. The only things that seem to be changed are metadata and comments in the pot file. Do we want to get this in even if the changes most likely won't be visible to the users?

**Comment by ofedoren** [comment]
I'd say why not? :) If it doesn't break anything though.

**Review by adamruzicka — APPROVED** [review]
Alright, lgtm

**Comment by adamruzicka** [comment]
Thank you @ofedoren

**Pull request merged**
