### PR TITLE
Fixes #7451 - Review whitespace in extracted strings

### PR DESCRIPTION
**Pull request by ofedoren**
depends on https://github.com/theforeman/hammer-cli/pull/265

### CODE REVIEW

**Comment by tstrachota** [comment]
Thanks for that huge effort @ofedoren I wrote simple tests that search through all the commands and check format of the messages. It found 187 issues.
See: https://github.com/theforeman/hammer-cli/pull/266 and https://github.com/theforeman/hammer-cli-foreman/pull/352

It's mostly success_messages (165x) but also some command descriptions (7x) and some other issues.

I'm not sure what was the final agreement. Should the success messages contain periods or not? @mbacovsky ?

**Comment by ofedoren** [comment]
@tstrachota done. Waiting for [merging](https://github.com/theforeman/hammer-cli-foreman/pull/352). Also needs [this](https://github.com/theforeman/foreman/pull/5230) to be merged.

**Comment by tstrachota** [comment]
Tests found only 3 issues that need to be fixed on server side in the api action descrptions first:
```
HammerCLIForeman::CommonParameter::ListCommand.desc ends with '.'
HammerCLIForeman::SmartProxy::ImportPuppetClassesCommand.desc ends with '.'
HammerCLIForeman::Filter::AvailableResourcesCommand.desc ends with '.'
```
Everything in the `hammer-cli-foreman`'s codebase has been fixed so I don't think it makes sense to block merging this PR for any longer.

The tests will run fine until we merge [my PR](https://github.com/theforeman/hammer-cli-foreman/pull/352) with punctuation checks. Once the server side PR gets merge we need to extract new version of API docs and add it to the tests in this repo.

**Comment by tstrachota** [comment]
[test]

**Comment by lzap** [comment]
I merged the core patch FYI

**Comment by tstrachota** [comment]
Merged, thanks @ofedoren. Kudos for your patience with fixing that 🥇

**Pull request merged**
