### PR TITLE
Fixes #31493 - Add support for vnic profile

### PR DESCRIPTION
**Pull request by shiramax**
- The pr depend on: https://github.com/theforeman/foreman/pull/8197 && https://github.com/fog/fog-ovirt/pull/98 to be merged first. 
- I also added here the tests data for foreman 2.4.

### CODE REVIEW

**Comment by shiramax** [comment]
@yifatmakias the foreman PR was merged, can you also please take a look at this one?

**Review by yifatmakias — APPROVED** [review]
Works as expected and looks good. nothing to change in my opinion :)

**Comment by shiramax** [comment]
@ofedoren can you please review?

**Review by ofedoren — APPROVED** [review]
Thanks, @shiramax! So sorry it took so long :rose:

LGTM, works as expected, although the test data contain resources which are not a part of plain Foreman. Do you have time to re-cache it for plain Foreman?

Otherwise it's ready for merge.

**Comment by shiramax** [comment]
done @ofedoren, thanks!

**Comment by ofedoren** [comment]
@shiramax, aaaand now the tests are failing :(

**Comment by ofedoren** [comment]
@shiramax, the tests are still failing, but it's not so related to hammer, but to foreman (API descriptions in API docs). We can merge it now, but the descriptions should be updated (I guess that could be a good easy task for new members). What do you think?

**Comment by shiramax** [comment]
yup. thanks @ofedoren I will open a Redmine issue for it, in the meantime, should I remove the dot from the foreman_api.json file? so we won't get failures?

**Comment by ofedoren** [comment]
@shiramax, ooof that would be great!

**Comment by shiramax** [comment]
done, the redmine: https://projects.theforeman.org/issues/31789

**Comment by ofedoren** [comment]
@shiramax, perfect, thanks! Merging.

**Pull request merged**
