### PR TITLE
Fixes #28984 - Adding location inherited parameters

### PR DESCRIPTION
**Pull request by shiramax**
Depend on: 
https://github.com/theforeman/foreman/pull/7434

### CODE REVIEW

**Comment by xprazak2** [comment]
Works well, lets wait until the changes in foreman are merged.

**Comment by shiramax** [comment]
@ofedoren thanks!
I'm not sure about this fix, I think it's a bit less readable, but it does remove a lot of repetitive code, 
If we will decide to choose your suggested fix, what do you think about all the parameters that are not Inherited? Do you think we should address them in the class as well?

**Comment by ofedoren** [comment]
@shiramax, if we choose my suggestion, then not inherited parameters are not required to be refactored, but I'd encourage the effort for this as well :) Maybe it's even possible to mix both ([non-]inherited) params within one class...

**Comment by shiramax** [comment]
thanks @ofedoren I will refactor it with the non-inherited params.
also, this PR can only be merged after theforeman/foreman#7434 will be merged.

**Pull request closed without merging**
