### PR TITLE
Fixes #3651 - Provides a way of listing compute attribute values

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by tstrachota** [comment]
@ofedoren this looks very good! Would you mind using functional tests instead of the unit ones? It's a preferred way of testing the commands with full api interactions.

**Comment by ofedoren** [comment]
@tstrachota sure. So should I remove the unit tests I added? After the functional tests are added of course.

**Comment by tstrachota** [comment]
Yeah, it makes sense to me to keep only the functional ones in this case.

**Comment by ofedoren** [comment]
@tstrachota, updated.

I added the functional tests and also changed the order of `Id` and `Name` fields, so it looks like the other `List` commands.

**Comment by mbacovsky** [comment]
@tstrachota, @ofedoren: Do we want to polish the NotImplemented errors or is it not a problem?
```
# hammer compute-resource clusters --id 1                                     
ERF42-7329 [Foreman::Exception]: Not implemented for Libvirt
```

**Comment by tstrachota** [comment]
Hmm, it's not that big deal for me but removing the "header" `ERF42-7329 [Foreman::Exception]:` would probably make it nicer. If it's too complicated to implement, I'm ok with leaving it as is.

**Comment by tstrachota** [comment]
Btw @ofedoren this is a great addition that many people will appreciate. It's a very nice candidate for the next community demo.

**Pull request merged**
