### PR TITLE
Fixes #33711 - Make sure provided options override defaults

### PR DESCRIPTION
**Pull request by ofedoren**
FTR: two tests are going to fail, but after https://github.com/theforeman/hammer-cli-foreman/pull/582 is merged, they hopefully will be green.

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]

**Comment by tbrisker** [comment]
@ofedoren I merged the other PR, care to rebase to ensure tests pass now?

**Comment by ofedoren** [comment]
[test hammer]

**Comment by ofedoren** [comment]
@tbrisker, thanks a lot for taking a look on this. Locally tests pass as well as for Ruby 2.7 on CI, but I'm not quite sure why it fails to run the tests on Ruby 2.5: https://ci.theforeman.org/job/test_hammer_cli_foreman_pull_request/500/ruby=2.5/console

**Review by tbrisker — APPROVED** [review]
Test failures are unrelated.

**Pull request merged**
