### PR TITLE
Fixes #28417 - Restrict Mocha to not use version > 1.9.0

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by ofedoren** [comment]
@shiramax, thanks, but could you provide more info why do we need this?..

**Comment by shiramax** [comment]
@ofedoren Mocha released a new version today that breaks test:
run bundle exec rake test
1) Error:
HammerCLIForeman::ExceptionHandler#test_0010_should print resource errors on internal error exception:
NoMethodError: undefined method `code' for " {\"error\":{\"message\":\"Some internal exception\"}}\n":String
Did you mean? encode
/home/mshira/.rvm/gems/ruby-2.5.1/gems/rest-client-2.0.2/lib/restclient/exceptions.rb:123:in `http_code'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/rest-client-2.0.2/lib/restclient/exceptions.rb:179:in `block (3 levels) in <module:RestClient>'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/rest-client-2.0.2/lib/restclient/exceptions.rb:142:in `message'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/rest-client-2.0.2/lib/restclient/exceptions.rb:162:in `to_s'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/mocha-1.10.1/lib/mocha/inspect.rb:9:in `inspect'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/mocha-1.10.1/lib/mocha/inspect.rb:9:in `mocha_inspect'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/mocha-1.10.1/lib/mocha/mockery.rb:130:in `on_stubbing'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/mocha-1.10.1/lib/mocha/object_methods.rb:129:in `block in stubs'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/mocha-1.10.1/lib/mocha/argument_iterator.rb:13:in `each'
/home/mshira/.rvm/gems/ruby-2.5.1/gems/mocha-1.10.1/lib/mocha/object_methods.rb:127:in `stubs'
/home/mshira/git/hammer-cli-foreman/test/unit/exception_handler_test.rb:95:in `block (2 levels) in <top (required)>'

I will later check if we could change the tests to support the new version as well
At the meantime, I think it's better to restrict the version so tests will not break

**Comment by shiramax** [comment]
@ofedoren already changed, try refresh :)

**Comment by ofedoren** [comment]
@shiramax, the title yes, but not the commit itself :) Otherwise the bot would've linked the redmine issue.

**Comment by shiramax** [comment]
@ofedoren yes, sorry. Done :)

**Comment by floehopper** [comment]
@shiramax @ofedoren It looks like you discovered a regression in Mocha. I've opened [a Mocha issue](https://github.com/freerange/mocha/issues/457) to track the problem and will try to release a fix as soon as I can. Sorry for adding this here - I couldn't work out how to add a comment to the Redmine issue referenced above.

**Comment by floehopper** [comment]
PR incoming: https://github.com/theforeman/hammer-cli-foreman/pull/476

**Pull request merged**
