### PR TITLE
Refs #28793 - Better promts for missing arguments

### PR DESCRIPTION
**Pull request by ofedoren**
Requires https://github.com/theforeman/hammer-cli/pull/322.

### CODE REVIEW

**Comment by xprazak2** [comment]
[test hammer]

**Comment by xprazak2** [comment]
Thanks!

**Comment by tbrisker** [comment]
looks like one of the tests is now failing? https://ci.theforeman.org/job/hammer-cli-foreman-master-source-release/80/

**Comment by ofedoren** [comment]
@tbrisker, should I raise a similar PR or we can wait until the test is fixed in one of the current PRs?

**Comment by tbrisker** [comment]
I'm not sure why it wasn't caught in this pr's test run, but please open a pr to update the failing test.

**Pull request merged**
