### PR TITLE
Fixes #28760 - Possibility to create IPv6 subnet

### PR DESCRIPTION
**Pull request by ofedoren**
Requires https://github.com/theforeman/hammer-cli/pull/326.

@lzap, since the issue is created by you, can you please verify this works as you'd expect?

The tests will probably fail because of old apidocs file. Tests rerun should be done after https://github.com/theforeman/foreman/pull/7437 is merged and the new `foreman_api.json` is provided.

### CODE REVIEW

**Comment by lzap** [comment]
Not good:

```
[lzap@box cli]$ hammer subnet create --name provisioning --network-type IPv6 --network fd00:aaaa:bbbb:ee::/64 --tftp-id 1 --discovery-id 1 --httpboot-id 1 --template-id 1 --domains dummy.lan
Could not create the subnet:
  Error: At least one of options --mask, --prefix is required.
  
  See: 'hammer subnet create --help'.

[lzap@box cli]$ hammer subnet create --name provisioning --network-type IPv6 --network fd00:aaaa:bbbb:ee:: --prefix 64 --tftp-id 1 --discovery-id 1 --httpboot-id 1 --template-id 1 --domains dummy.lan
Could not create the subnet:
  Missing arguments for '--mask'.
```
I definitely don'ŧ want to enter IPv6 mask manually, just prefix must be enough :-)

**Comment by ofedoren** [comment]
@lzap, yes I'm aware of required mask and https://github.com/theforeman/foreman/pull/7437 fixed this.

Try to reload cache with `hammer --reload-cache`.

After that the command will require mask OR prefix, not both.

**Comment by lzap** [comment]
Thing is, I actually reload the cache on every request:

    alias hammer='cd ~/work/hammer/cli && be bin/hammer -u admin -p changeme -r'

It does not work for me. Do I need to perform some cache regeneration command on my development setup?

**Comment by lzap** [comment]
Performed `rake apipie:cache` without any success.

**Comment by ofedoren** [comment]
@lzap, thanks a lot for testing! Unfortunatelly I can't reproduce your error :( I've tried
```sh
hammer subnet create --name test_provisioning --network-type IPv6 --network fd00:aaaa:bbbb:ee:: --prefix 64 --tftp-id 1 --discovery-id 1 --httpboot-id 1 --template-id 1 --domains local.com
```

and it worked:
ScreenShot-1582721939490

If you ran `rake apipie:cache` on the server siide and then `hammer --reload-cache` and it still doesn't work, I'd assume that the foreman checkout doesn't have the fix from https://github.com/theforeman/foreman/pull/7437

**Comment by xprazak2** [comment]
Works for me, test failures seem related.

subnet-v6

**Comment by ofedoren** [comment]
@xprazak2, thanks! Related failures should go away after https://github.com/theforeman/hammer-cli-foreman/pull/506 is merged.

**Comment by xprazak2** [comment]
Apidoc update has been merge, I suspect this will need a rebase.

**Comment by lzap** [comment]
Hmmm anything else I can do with my dev setup to get it working?

**Comment by ofedoren** [comment]
@lzap, rebased. Do you still have issues?

**Comment by lzap** [comment]
Well it works and I don't want to delay this but it's weird syntax:

```
[lzap@box cli]$ hammer subnet create --name provisioning --network-type IPv6 --network fd00:aaaa:bbbb:ee::/64 --tftp-id 1 --discovery-id 1 --httpboot-id 1 --template-id 1 --domains dummy.lan
Could not create the subnet:
  Error: At least one of options --mask, --prefix is required.
  
  See: 'hammer subnet create --help'.
[lzap@box cli]$ hammer subnet create --name provisioning --network-type IPv6 --network fd00:aaaa:bbbb:ee:: --prefix 64 --tftp-id 1 --discovery-id 1 --httpboot-id 1 --template-id 1 --domains dummy.lan
Subnet created.
```

I'd expect CIDR would work too.

**Comment by lzap** [comment]
I don't have permission to merge tho.

**Comment by xprazak2** [comment]
I do :wink: , thanks everyone!

**Pull request merged**
