### PR TITLE
Refs #27868 - Fix method typo

### PR DESCRIPTION
**Pull request by ofedoren**
This should also be cherry-picked to 0.18-stable, so we can release 0.18.2.

### CODE REVIEW

**Comment by mbacovsky** [comment]
To make the tests green we need to resolve https://github.com/theforeman/hammer-cli-foreman/pull/443

**Comment by mbacovsky** [comment]
The patch looks good and it works as expected. The failing tests are unrelated.
Can we have some test to avoid future breakages?

**Comment by ofedoren** [comment]
@mbacovsky, thanks. I've added a test.

**Comment by tbrisker** [comment]
Looks like the test failures are related, this is now failing in the nightly pipeline: https://ci.theforeman.org/job/hammer-cli-foreman-master-source-release/41/

**Comment by mbacovsky** [comment]
@tbrisker PR https://github.com/theforeman/hammer-cli-foreman/pull/443 provides fix for the tests. The failures are caused by recent change in hammer-cli.

**Comment by tbrisker** [comment]
> @tbrisker PR #443 provides fix for the tests. The failures are caused by recent change in hammer-cli.

sorry, i should have read the previous comments.

**Pull request merged**
