### PR TITLE
Refs #12473 - show admin flag in user-group listing

### PR DESCRIPTION
**Pull request by mbacovsky**
The API already sends the admin flag in its responses so no changes on the server side are not necessary.
Note: to create admin user group with hammer you will need https://github.com/theforeman/foreman/pull/3705 merged in though.

### CODE REVIEW

**Comment by mbacovsky** [comment]
Ruby 2.0 tests are waiting for https://github.com/theforeman/hammer-cli/pull/198.

**Comment by mbacovsky** [comment]
[test]

**Comment by tstrachota** [comment]
Works as expected. Ack once the tests are green.

**Comment by tstrachota** [comment]
@mbacovsky tests are failing due to latest fast_gettext. Fix is here: https://github.com/theforeman/hammer-cli-foreman/pull/257

**Comment by mbacovsky** [comment]
[test]

**Comment by tstrachota** [comment]
:+1: thanks @mbacovsky

**Pull request merged**
