### PR TITLE
Fixes #16772 - Added description field to User in hammer

### PR DESCRIPTION
**Pull request by dhlavac**

### CODE REVIEW

**Comment by ares** [comment]
LGTM :+1:

**Comment by tstrachota** [comment]
Merged as https://github.com/theforeman/hammer-cli-foreman/commit/30a072e56757fd43fcf9e2f9daf8884ac29bcc6e Thanks @dhlavac !

**Comment by tstrachota** [comment]
Closed by mistake instead of #261, I'm sorry. They are too similar and even have the same comment from @ares ! :)

**Comment by tstrachota** [comment]
:+1: thanks @dhlavac

**Pull request merged**
