### PR TITLE
fixes #19134 - add vlan id field to subnet

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by ares** [comment]
:+1: from me, works fine

**Comment by tstrachota** [comment]
Thanks @timogoebel 
We already have that field defined for the `info` command, which inherits the field definition from `list` (https://github.com/timogoebel/hammer-cli-foreman/blob/7ec4ca90252ec3babb87ee70520e440af0914d8c/lib/hammer_cli_foreman/subnet.rb#L31). Can you please remove vlan id from `info` in your commit to prevent it from being printed twice? We should probably also keep the label in capitals for backward compatibility.

**Comment by timogoebel** [comment]
@tstrachota : Updated. Thanks. Did not spot that...

**Comment by ares** [comment]
oh I missed that but I can confirm that it now displays just once

**Comment by tstrachota** [comment]
Thank you @timogoebel

**Pull request merged**
