### PR TITLE
[CP] Picks for 0.15.2

### PR DESCRIPTION
**Pull request by jturel**
This is in support of Katello 3.10.1 => https://github.com/Katello/hammer-cli-katello/pull/639

### CODE REVIEW

**Comment by jturel** [comment]
[test hammer]

**Comment by jturel** [comment]
@mbacovsky can you help me out with a release for this?

**Comment by jturel** [comment]
@tbrisker may I interest you in doing a release for hammer-cli-foreman?

**Comment by mbacovsky** [comment]
Just for a record: we agreed on limiting deps on hammer-cli < 0.16 and releasing a new gem. It is not necessary to do a new rpm/deb release as the issue can be only reproduced on gem based installs.

**Comment by jturel** [comment]
If I'm understanding the test failure right, I think the culprit is:

https://github.com/theforeman/foreman-infra/blob/50d36964d0e2b286e9466e7ebce0feae7e6b014e/puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman_pull_request.sh#L17

Tests pass locally, but fail in Jenkins:

```
20:33:10 Bundler could not find compatible versions for gem "hammer_cli":
20:33:10   In Gemfile:
20:33:10     hammer_cli
20:33:10 
20:33:10     hammer_cli_foreman was resolved to 0.15.2, which depends on
20:33:10       hammer_cli (>= 0.15.1, < 0.16.0)
20:33:10 
20:33:10 Could not find gem 'hammer_cli (>= 0.15.1, < 0.16.0)', which is required by gem
20:33:10 'hammer_cli_foreman', in any of the relevant sources:
20:33:10   git://github.com/theforeman/hammer-cli.git (at master@107a512)
```

**Comment by mbacovsky** [comment]
@jturel thanks for the patch. I guess you are right with the cause. It would make more sense to test against master only if the PR target is master and let bundler install hammer-cli from gems otherwise. Are you familiar with Jenkins job builder scripts?

**Comment by jturel** [comment]
@mbacovsky this might do the trick: https://github.com/theforeman/foreman-infra/pull/1026

**Comment by mbacovsky** [comment]
[test hammer]

**Comment by mbacovsky** [comment]
[hammer test]

**Comment by mbacovsky** [comment]
[test hammer]

**Comment by mbacovsky** [comment]
@jturel new gem was pushed to rg.o. Thanks for your help!

**Comment by jturel** [comment]
[test hammer]

**Pull request merged**
