### PR TITLE
Fixes #26019 - display uptime

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by mbacovsky** [comment]
@ares thanks for the patch!
Please rebase the PR it is not compatible with latest hammer-cli and the tests fail.
Also what is the setup when the uptime is part of the host data? Is it a new feature in core?

**Comment by ares** [comment]
rebased
yes, it needs https://github.com/theforeman/foreman/pull/6458 :-)

**Comment by mbacovsky** [comment]
Thanks, looks good now, I'll wait  with merging till the core PR is merged.

**Comment by tbrisker** [comment]
core has been merged

**Comment by mbacovsky** [comment]
@tbrisker thanks for the heads up!

**Pull request merged**
