### PR TITLE
fixes #13966 - newer version of apipie validates types for arrays

### PR DESCRIPTION
**Pull request by tstrachota**
Therefore we no longer can send network interfaces in hashes even though
the server would cope with it.

The PR also fixes api mocking and expectations that used to skip param validations.

### CODE REVIEW

**Comment by domcleal** [comment]
Note the commit message is missing a `#` before the ticket number.

**Comment by tstrachota** [comment]
Oops, good catch @domcleal Fixed

**Comment by tstrachota** [comment]
The related apipie-bindings PR has been merged, waiting for a new release now.

**Comment by iNecas** [comment]
Tested and works well, also no code comments. Clean :+1:. Thanks @tstrachota !

**Pull request merged**
