### PR TITLE
Fixes #36315 - Update TX for hammer-cli-foreman

### PR DESCRIPTION
**Pull request by ofedoren**
Requires https://github.com/theforeman/hammer-cli/pull/366.

### CODE REVIEW

**Comment by adamruzicka** [comment]
I applied the whole hammer-cli changes and only the first commit from here to try pulling those translations myself. This is what I'm getting
```shell
# make -C locale tx-update
make: Entering directory 'hammer-cli-foreman/locale'
No permissions to create log dir /var/log/hammer.
File /var/log/hammer/hammer.log not writeable, won't log anything to the file!
No permissions to create log dir /var/log/hammer.
File /var/log/hammer/hammer.log not writeable, won't log anything to the file!
bundle exec rake gettext:find_new
(in hammer-cli-foreman)
bundle exec rake gettext:find
(in hammer-cli-foreman)
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ca/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ca/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ca/hammer-cli-foreman.edit.po
Warning: obsolete msgid exists.
         #~ msgid "Zone"
Warning: obsolete msgid exists.
         #~ msgstr "Zona"
Warning: obsolete msgid exists.
         #~ msgid "Machine Type"
Warning: obsolete msgid exists.
         #~ msgstr "Tipus de màquina"
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ca/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/de/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/de/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/de/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/de/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/en/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/en/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/en/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/en/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/en_GB/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/en_GB/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/en_GB/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/en_GB/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/es/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/es/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/es/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/es/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/fr/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/fr/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/fr/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/fr/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/it/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/it/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/it/hammer-cli-foreman.edit.po
Warning: obsolete msgid exists.
         #~ msgid "Zone"
Warning: obsolete msgid exists.
         #~ msgstr "Zona"
Warning: obsolete msgid exists.
         #~ msgid "Machine Type"
Warning: obsolete msgid exists.
         #~ msgstr "Tipo di macchina"
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/it/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ja/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ja/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ja/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ja/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ko/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ko/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ko/hammer-cli-foreman.edit.po
Warning: obsolete msgid exists.
         #~ msgid "Zone"
Warning: obsolete msgid exists.
         #~ msgstr "영역 "
Warning: obsolete msgid exists.
         #~ msgid "Machine Type"
Warning: obsolete msgid exists.
         #~ msgstr "시스템 유형 "
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ko/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/pt_BR/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/pt_BR/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/pt_BR/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/pt_BR/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ru/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ru/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ru/hammer-cli-foreman.edit.po
Warning: obsolete msgid exists.
         #~ msgid "Zone"
Warning: obsolete msgid exists.
         #~ msgstr "Зона"
Warning: obsolete msgid exists.
         #~ msgid "Machine Type"
Warning: obsolete msgid exists.
         #~ msgstr "Тип машины"
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ru/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/zh_CN/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/zh_CN/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/zh_CN/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/zh_CN/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/zh_TW/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/zh_TW/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/zh_TW/hammer-cli-foreman.edit.po
Warning: obsolete msgid exists.
         #~ msgid "Zone"
Warning: obsolete msgid exists.
         #~ msgstr "區域"
Warning: obsolete msgid exists.
         #~ msgid "Machine Type"
Warning: obsolete msgid exists.
         #~ msgstr "機器類型"
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/zh_TW/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ka/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ka/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ka/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/ka/hammer-cli-foreman.po.time_stamp
rm -f hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/cs_CZ/hammer-cli-foreman.edit.po
cp hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/cs_CZ/hammer-cli-foreman.po hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/cs_CZ/hammer-cli-foreman.edit.po
touch hammer-cli-foreman/lib/hammer_cli_foreman/../../locale/cs_CZ/hammer-cli-foreman.po.time_stamp
cd .. && tx pull -f foreman.hammer_cli_foreman
usage: tx [-h] [-l LANGUAGES] [-r RESOURCES] [-a] [-s] [-f] [--skip]
          [--disable-overwrite] [--minimum-perc MINIMUM_PERC] [--pseudo]
          [--use-git-timestamps] [--mode MODE] [-b [BRANCH]] [-x] [--parallel]
          [--no-interactive]
tx: error: unrecognized arguments: foreman.hammer_cli_foreman
make: *** [hammer-cli/locale/Makefile.def:64: tx-pull] Error 2
make: Leaving directory 'hammer-cli-foreman/locale'
```

What am I missing?

**Comment by ofedoren** [comment]
> 
> What am I missing?

I guess you have old version of `tx-client`?

Mine is:
```sh
$ tx --version
TX Client, version=1.6.5
```

**Comment by adamruzicka** [comment]
Or new version? O.o
```
# tx --version                                
0.14.4, py 3.9, x86_64
```

**Comment by ofedoren** [comment]
> Or new version? O.o
> 
> ```
> # tx --version                                
> 0.14.4, py 3.9, x86_64
> ```

This is rather the old one written in Python: https://pypi.org/project/transifex-client/

There is also a note:
> A new client, compatible with the [new API](https://transifex.github.io/openapi/), is under development. Check out the Alpha version [here](https://github.com/transifex/cli).

I'm using the new client (https://developers.transifex.com/docs/cli), which is in Go and designed for the new API. Eventually we would need to switch to that anyway, thus why I'm changing `.tx/config`.

> 
> ```
> $ make -C locale vars
> # ...
> VERSION: 3.7.0.pre.develop
> DOMAIN: hammer_cli_foreman
> ```

This is weird. This can happen if your local checkout of hammer-cli-foreman is not properly loaded, so instead of using actual domain it guessed and used the gem's name. Could you check if you have `foreman.yml` in `~/.hammer/cli.modules.d/`? Also, what `hammer --version` shows?

**Review by adamruzicka — COMMENTED** [review]
ACK, pending the main hammer-cli PR

**Comment by ofedoren** [comment]
Closing in favor of https://github.com/theforeman/hammer-cli-foreman/pull/616

**Pull request closed without merging**
