### PR TITLE
Fixes #26536 - Possibility to change host loc/org via hammer (#416)

### PR DESCRIPTION
**Pull request by ofedoren**
(cherry picked from commit 031522dc6ba5480c1d4d8820249698818c3aacae)

### CODE REVIEW

**Comment by ofedoren** [comment]
@mbacovsky, nothing new, just a CP, but could you take a look in a case of anything? :)

**Comment by mbacovsky** [comment]
@ofedoren thanks for the CP. Do we need also CP in hammer-cli-katello (https://github.com/Katello/hammer-cli-katello/commit/4b595a257a37a3e540ee7a188afb6f099b48776c)?

**Comment by ofedoren** [comment]
@mbacovsky. I don't think so, that commit conatins only a small fix for a test that I made. Also, I've run tests locally against 0.17-stable with this CP and they pass for 0.18.z and 0.19.z for katello.

@akofink, if we need to do a CP as @mbacovsky suggested, against what branch should I do it?

**Comment by mbacovsky** [comment]
@ofedoren I can see one test failing on my fresh h-c-k 0.18.z against the new CP:
```
  1) Failure:
HammerCLIForeman::Host::HammerCLIForeman::UpdateCommand#test_0001_allows kickstart repository name [/home/mbacovsk/.rvm/gems/ruby-2.5.3/gems/apipie-bindings-0.2.3/lib/apipie_bindings/api.rb:185]:
unexpected invocation: #<AnyInstance:ApipieBindings::API>.call_action(<Action hosts:update>, {"organization_id" => 329, "id" => "777", "host" => {"puppetclass_ids" => [], "compute_attributes" => {}, "content_facet_attributes" => {"content_view_id" => 200, "lifecycle_environment_id" => 100, "kickstart_repository_id" => 111}, "subscription_facet_attributes" => {}}}, {}, {:fake_response => nil})
unsatisfied expectations:
- expected exactly once, not yet invoked: 
  #<AnyInstance:ApipieBindings::API>.call_action(:hosts, :update, *any_argument)
  expected params to include: {
    "id": "777",
    "host": {
      "organization_id": 329,
      "content_facet_attributes": {
        "lifecycle_environment_id": 100,
        "content_view_id": 200,
        "kickstart_repository_id": 111
      }
    }
  }
satisfied expectations:
- expected exactly once, invoked once: 
  #<AnyInstance:ApipieBindings::API>.call_action(:repositories, :index, *any_argument)
  expected params to include: {
    "name": "life_of_kickstart",
    "environment_id": 100,
    "content_view_id": 200
  }
- expected exactly once, invoked once: 
  #<AnyInstance:ApipieBindings::API>.call_action(:lifecycle_environments, :index, *any_argument)
  expected params to include: {
    "name": "world",
    "organization_id": 329
  }


561 tests, 1632 assertions, 1 failures, 0 errors, 0 skips
```
It looks similar to what has to be fixed when the original PR was introduced.

**Comment by ofedoren** [comment]
@mbacovsky, thanks for pointing me :) See https://github.com/Katello/hammer-cli-katello/pull/691

**Pull request merged**
