### PR TITLE
Fixes #9114 - User info doesn't display timezone and locale

### PR DESCRIPTION
**Pull request by tstrachota**
Please test together with https://github.com/theforeman/foreman/pull/2110

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tstrachota if this works against foreman 1.7, am I sane to assume that hammer simply does not show those fields? (based on api description)?

**Comment by tstrachota** [comment]
@ohadlevy I did a small update. Hammer now shows empty fields for locale on 1.7 with this patch. The rest works.

**Comment by tstrachota** [comment]
[test]

**Comment by mbacovsky** [comment]
:+1:  Looks good. Thanks @tstrachota

**Pull request merged**
