### PR TITLE
Refs #29413 - Add aliases for info/list/delete commands

### PR DESCRIPTION
**Pull request by ofedoren**
Requires https://github.com/theforeman/hammer-cli/pull/327.

### CODE REVIEW

**Comment by xprazak2** [comment]
Works! I suppose tests will turn green when the required hammer-cli changes get in....

**Comment by shiramax** [comment]
@ofedoren please rebase :)

**Comment by ofedoren** [comment]
@shiramax, done :)

**Comment by shiramax** [comment]
thanks @ofedoren !

**Pull request merged**
