### PR TITLE
Fixes #7473 - puppet-classes in host and hostgroup returns without an error

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
Works well, @orrabin 
There are some redundant parameters in `host[group] puppet-classes` commands. E.g. it doesn't make much sense to use `--environment` for them.

You can remove them easily. See:
https://github.com/tstrachota/hammer-cli-foreman/commit/9dcbefb3c23b506aa212b2f047183110279c2f5f

**Comment by orrabin** [comment]
@tstrachota thanks for the help, I have removed the redundant parameters and rebased

**Comment by tstrachota** [comment]
:+1: Thank you @orrabin

**Pull request merged**
