### PR TITLE
Refs #26008 - parameter type to parameter commands

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Adds parameter_type.

I have realized it is going to be addressed already in the middle of the process.
I have found @kgaikwad work, but as in the process, I realized we need to do a bit more anyway.

Sorry @kgaikwad for being sloppy and not looking before starting to code :(
But I would suggest merging #409 first and I will rebase my work on that one, as there is default value addressed, that I forgot and should be in other resources as well.

### CODE REVIEW

**Comment by ofedoren** [comment]
@ezr-ondrej, https://github.com/theforeman/hammer-cli-foreman/pull/409 is merged, so this needs a rebase.

**Comment by kgaikwad** [comment]
@ezr-ondrej,
no worries! :-) 
:+1:  for extraction of data types into a constant.

**Comment by ezr-ondrej** [comment]
@ofedoren yeah, I believe it's ready :)

**Comment by ofedoren** [comment]
@ezr-ondrej, merging then, thanks! :)

**Pull request merged**
