### PR TITLE
Fixes #12090 - Allows 0.4 to work with foreman 1.10-dev

### PR DESCRIPTION
**Pull request by dgagnon**
This fixes the problem for me and allows me to use foreman-cli with the nightly.

### CODE REVIEW

**Comment by mbacovsky** [comment]
[test]

**Comment by dgagnon** [comment]
need anything else mbacovsky   ?

**Comment by mbacovsky** [comment]
@dgagnon thanks for the PR, it looks good. I'll just have to test it before it is merged.

**Comment by tstrachota** [comment]
@mbacovsky I tested the patch and it works well, merging. Thanks @dgagnon !

**Pull request merged**
