### PR TITLE
Fixes #14725 - Verbose mode does not work and is inconsistent

### PR DESCRIPTION
**Pull request by ofedoren**
depends on https://github.com/theforeman/hammer-cli/pull/263

### CODE REVIEW

**Comment by tstrachota** [comment]
Would it be possible to provide verbosity in the default context instead of passing it everywhere in the tests explicitly?

**Comment by ofedoren** [comment]
@tstrachota, I've made some changes in hammer core, so there is no more need to pass default verbosity everywhere explicitly. Only a few little changes are needed now.

**Comment by tstrachota** [comment]
@ofedoren if I understand it correctly this PR is no longer needed with the latest changes in https://github.com/theforeman/hammer-cli/pull/263 right?

**Comment by ofedoren** [comment]
@tstrachota correct. This PR is no longer needed.

**Comment by tstrachota** [comment]
Ok, thanks for confirmation, I'm closing it.

**Pull request closed without merging**
