### PR TITLE
Fixes #18663 - Fix added with set and delete parameters

### PR DESCRIPTION
**Pull request by dhlavac**
`--subnet-parameters-attributes` was removed and replaced by -
`hammer subnet set-parameter` and  `hammer subnet delete-parameter`

### CODE REVIEW

**Comment by tstrachota** [comment]
Thanks for the patch @dhlavac Where's the code that removes `--subnet-parameters-attributes`, please?

**Comment by dhlavac** [comment]
@tstrachota updated ... code to remove  `--subnet-parameters-attributes`

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
Looks good and works fine now. @dhlavac could you add list of parameters to `subnet info`, please? See my PR https://github.com/dhlavac/hammer-cli-foreman/pull/1

**Comment by dhlavac** [comment]
Thanks @tstrachota merged your PR, works fine

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
Thanks @dhlavac, merged.

**Pull request merged**
