### PR TITLE
Refs #7451 - tests for message formats

### PR DESCRIPTION
**Pull request by tstrachota**
Testing messages for the foreman commands.
Requires: https://github.com/theforeman/hammer-cli/pull/266

### CODE REVIEW

**Comment by mmoll** [comment]
[test]

**Comment by mmoll** [comment]
now with more correct failing ;)

**Comment by tstrachota** [comment]
Cool, the failing tests are caused by strings that come from apidoc. I'll need to extract and include newer apipie cache.

**Comment by tstrachota** [comment]
[test]

**Comment by komidore64** [comment]
[test hammer]

**Comment by mmoll** [comment]
[test default]

**Comment by iNecas** [comment]
Test failures related: probably due to fact that some non-compliant messages were introduced to hammer in the mean time.

**Comment by tstrachota** [comment]
[test]

**Comment by ofedoren** [comment]
@tstrachota, I'd say it's good to go, tests are green on local running.

**Comment by mbacovsky** [comment]
[test hammer]

**Comment by mbacovsky** [comment]
:+1: Well done! Thanks @tstrachota, @ofedoren

**Pull request merged**
