### PR TITLE
Refs #28135 - Remove URL field from GCE info

### PR DESCRIPTION
**Pull request by ofedoren**
This should be also cherry-picked into 0.19-stable for 0.19.5.

### CODE REVIEW

**Comment by xprazak2** [comment]
Before:

url-before

After: 

url-after

I haven't tested vmware, ec2, ovirt and rackspace - but openstack and libvirt show url correctly and given they all use the same code, I do not see a reason why the rest of the compute resources would not show the field properly.
I think this is ready unless someone wants to test those remaining CRs.

**Comment by ofedoren** [comment]
@shiramax, I think we could stop including `url` attribute in JSON responses from API for GCE info, but it isn't backward compatible, is it?

**Comment by shiramax** [comment]
@ofedoren OK, I checked with foreman, and it seems like this is the best option. thanks @ofedoren !

**Comment by kgaikwad** [comment]
@ofedoren, @shiramax, 
any updates on this? can we merge this PR?

**Comment by ofedoren** [comment]
@kgaikwad, sure, if nobody has concerns, it's ready.

**Comment by kgaikwad** [comment]
@shiramax, This change should be also cherry-picked into 0.19-stable.

**Comment by ofedoren** [comment]
@kgaikwad, I think we need a CP for this into 0.19-stable. Do you want to do it or should I?

**Comment by kgaikwad** [comment]
@ofedoren, 
Either way will work for me. As I didn't see any CP PR so asked. It would be good if you do it as original PR created by you.

**Pull request merged**
