### PR TITLE
Fixes #31570 - consume structured statuses API data

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
the normalize code can also be completely dropped if we only want to support foreman releases with the structured data

**Comment by evgeni** [comment]
I have no idea why CI fails now, but it's not my change. (it was green before I amended the subject)

**Comment by evgeni** [comment]
oh, cool, cool: https://github.com/rubygems/rubygems/issues/4229

**Comment by tbrisker** [comment]
[test hammer]

**Review by shiramax — APPROVED** [review]

**Comment by shiramax** [comment]
thanks @evgeni

**Comment by shiramax** [comment]
thanks @evgeni could we have tests for this?

**Comment by evgeni** [comment]
I guess so. Let me see.

**Comment by evgeni** [comment]
@shiramax there, added tests for old and new behaviour, and learned something about Ruby… ;)

**Review by shiramax — APPROVED** [review]

**Comment by shiramax** [comment]
thanks @evgeni !

**Pull request merged**
