### PR TITLE
Fixes #28176 - Add http-proxy to hammer

### PR DESCRIPTION
**Pull request by chris1984**
This PR adds the basic CRUD operations for http-proxies to Hammer

### CODE REVIEW

**Comment by chris1984** [comment]
@jjeffers here is the pr for adding http-proxies to katello

**Comment by chris1984** [comment]
@ofedoren can I get a review please when you get time

**Comment by ofedoren** [comment]
@chris1984, sure thing. I've already took a look at the code and code-wise LGTM. Didn't tested though.. Also, just for the sake of consistency, it would be nice to have a test also for update command.

**Comment by chris1984** [comment]
@ofedoren sounds good will work on the changes you requested and resubmit. Thanks for the review.

**Comment by chris1984** [comment]
@ofedoren updated with info and made new tests for info and update. Also moved the test into the correct folder which I didnt catch before. @jjeffers care to test?

**Pull request merged**
