### PR TITLE
Fixes #22988 - show cidr notation

### PR DESCRIPTION
**Pull request by sean797**

### CODE REVIEW

**Comment by mbacovsky** [comment]
[test]

**Comment by sean797** [comment]
ping?

**Comment by akofink** [comment]
[test]

**Comment by ofedoren** [comment]
[test]

**Comment by ofedoren** [comment]
[test]

**Comment by sean797** [comment]
rebased

**Comment by tstrachota** [comment]
Works fine, tests are green, merging. Thanks @sean797 !

**Pull request merged**
