### PR TITLE
Fixes #3036, #12587, #3956 - Ping command

### PR DESCRIPTION
**Pull request by ofedoren**
Requires https://github.com/theforeman/foreman/pull/6794 and https://github.com/theforeman/hammer-cli/pull/291 to be merged first.

Also there will be need to update `foreman_api.json` after that PR is merged. Until then tests will be red.

### CODE REVIEW

**Comment by evgeni** [comment]
[test hammer]

**Comment by evgeni** [comment]
@ofedoren I think you need to update the tests to have a 1.24/develop apidoc.json for this to pass.

**Comment by ofedoren** [comment]
@evgeni, done. The test failures are not related to this PR.

**Comment by chris1984** [comment]
[test hammer]

**Comment by chris1984** [comment]
@mbacovsky can this get merged, I acked it. Once it is merged here I will merge the hammer-katello one.

**Comment by ofedoren** [comment]
Also, I've updated `foreman_api.json`, so test should be green now.

**Pull request merged**
