### PR TITLE
fixes #19156 - compute-resources has images subcommand

### PR DESCRIPTION
**Pull request by timogoebel**

### CODE REVIEW

**Comment by tstrachota** [comment]
Nice addition @timogoebel 
Would you mind adding a check if `--name` and `--id` options are present?
```ruby
validate_options do
  any(:option_id, :option_name).required
end
```

FYI we started adding tests for new commands into `functional/`. They're a bit more verbose but enable testing in the context of whole cli and provide more readable failure messages when things go wrong.

**Comment by timogoebel** [comment]
@tstrachota : Thanks. Added the validations.

**Comment by tstrachota** [comment]
@timogoebel cool. The tests failed because they now expect the options.

**Comment by timogoebel** [comment]
@tstrachota : Fixed the tests, thanks.

**Comment by tstrachota** [comment]
Merged, thanks @timogoebel !

**Pull request merged**
